language: node_js

node_js:
  - "node"

sudo: false

services:
  - mongodb

before_script:
  - "until nc -z localhost 27017 ; do echo Waiting for MongoDB; sleep 1; done"

script:
  - npm run lint
  - npm run test

after_success:
  - "npm run-script coveralls"
